export const INITIALIZE_PRODUCTS = 'INITIALIZE_PRODUCTS';
export const APPROVE_PRODUCT = 'APPROVE_PRODUCT';
export const MARK_MISSING = 'MARK_MISSING';
// export const OPEN_EDIT_POPUP = 'OPEN_EDIT_POPUP';
// export const CLOSE_EDIT_POPUP = 'CLOSE_EDIT_POPUP';
// export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';